parameters:
#    formacion.example.class: BecasMds\FormacionBundle\Example

services:
#    formacion.example:
#        class: %formacion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
