<?php

namespace Proxies\__CG__\BecasMds\BecaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class BecadoBeca extends \BecasMds\BecaBundle\Entity\BecadoBeca implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setFechaAlta($fechaAlta)
    {
        $this->__load();
        return parent::setFechaAlta($fechaAlta);
    }

    public function getFechaAlta()
    {
        $this->__load();
        return parent::getFechaAlta();
    }

    public function setFechaBaja($fechaBaja)
    {
        $this->__load();
        return parent::setFechaBaja($fechaBaja);
    }

    public function getFechaBaja()
    {
        $this->__load();
        return parent::getFechaBaja();
    }

    public function setActivo($activo)
    {
        $this->__load();
        return parent::setActivo($activo);
    }

    public function getActivo()
    {
        $this->__load();
        return parent::getActivo();
    }

    public function setDetalles($detalles)
    {
        $this->__load();
        return parent::setDetalles($detalles);
    }

    public function getDetalles()
    {
        $this->__load();
        return parent::getDetalles();
    }

    public function setBecado(\BecasMds\PersonaBundle\Entity\Becado $becado = NULL)
    {
        $this->__load();
        return parent::setBecado($becado);
    }

    public function getBecado()
    {
        $this->__load();
        return parent::getBecado();
    }

    public function setBeca(\BecasMds\BecaBundle\Entity\Beca $beca = NULL)
    {
        $this->__load();
        return parent::setBeca($beca);
    }

    public function getBeca()
    {
        $this->__load();
        return parent::getBeca();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function addCertificacion(\BecasMds\CertificacionBundle\Entity\Certificacion $certificacion)
    {
        $this->__load();
        return parent::addCertificacion($certificacion);
    }

    public function removeCertificacion(\BecasMds\CertificacionBundle\Entity\Certificacion $certificacion)
    {
        $this->__load();
        return parent::removeCertificacion($certificacion);
    }

    public function getCertificacion()
    {
        $this->__load();
        return parent::getCertificacion();
    }


    public function __sleep()
    {
        return array_merge(array('__isInitialized__'), parent::__sleep());
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}