<?php

namespace Proxies\__CG__\BecasMds\PersonaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Domicilio extends \BecasMds\PersonaBundle\Entity\Domicilio implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNumero($numero)
    {
        $this->__load();
        return parent::setNumero($numero);
    }

    public function getNumero()
    {
        $this->__load();
        return parent::getNumero();
    }

    public function setDpto($dpto)
    {
        $this->__load();
        return parent::setDpto($dpto);
    }

    public function getDpto()
    {
        $this->__load();
        return parent::getDpto();
    }

    public function setPiso($piso)
    {
        $this->__load();
        return parent::setPiso($piso);
    }

    public function getPiso()
    {
        $this->__load();
        return parent::getPiso();
    }

    public function setEdificio($edificio)
    {
        $this->__load();
        return parent::setEdificio($edificio);
    }

    public function getEdificio()
    {
        $this->__load();
        return parent::getEdificio();
    }

    public function setManzana($manzana)
    {
        $this->__load();
        return parent::setManzana($manzana);
    }

    public function getManzana()
    {
        $this->__load();
        return parent::getManzana();
    }

    public function setTira($tira)
    {
        $this->__load();
        return parent::setTira($tira);
    }

    public function getTira()
    {
        $this->__load();
        return parent::getTira();
    }

    public function setParcela($parcela)
    {
        $this->__load();
        return parent::setParcela($parcela);
    }

    public function getParcela()
    {
        $this->__load();
        return parent::getParcela();
    }

    public function setQuinta($quinta)
    {
        $this->__load();
        return parent::setQuinta($quinta);
    }

    public function getQuinta()
    {
        $this->__load();
        return parent::getQuinta();
    }

    public function setUnidadFuncional($unidadFuncional)
    {
        $this->__load();
        return parent::setUnidadFuncional($unidadFuncional);
    }

    public function getUnidadFuncional()
    {
        $this->__load();
        return parent::getUnidadFuncional();
    }

    public function setTipoDomicilio($tipoDomicilio)
    {
        $this->__load();
        return parent::setTipoDomicilio($tipoDomicilio);
    }

    public function getTipoDomicilio()
    {
        $this->__load();
        return parent::getTipoDomicilio();
    }

    public function setLatitude($latitude)
    {
        $this->__load();
        return parent::setLatitude($latitude);
    }

    public function getLatitude()
    {
        $this->__load();
        return parent::getLatitude();
    }

    public function setLongitude($longitude)
    {
        $this->__load();
        return parent::setLongitude($longitude);
    }

    public function getLongitude()
    {
        $this->__load();
        return parent::getLongitude();
    }

    public function setReferencias($referencias)
    {
        $this->__load();
        return parent::setReferencias($referencias);
    }

    public function getReferencias()
    {
        $this->__load();
        return parent::getReferencias();
    }

    public function setLocalidad(\BecasMds\PersonaBundle\Entity\Localidad $localidad = NULL)
    {
        $this->__load();
        return parent::setLocalidad($localidad);
    }

    public function getLocalidad()
    {
        $this->__load();
        return parent::getLocalidad();
    }

    public function setDepartamento(\BecasMds\PersonaBundle\Entity\Departamento $departamento = NULL)
    {
        $this->__load();
        return parent::setDepartamento($departamento);
    }

    public function getDepartamento()
    {
        $this->__load();
        return parent::getDepartamento();
    }

    public function setBarrio(\BecasMds\PersonaBundle\Entity\Barrio $barrio = NULL)
    {
        $this->__load();
        return parent::setBarrio($barrio);
    }

    public function getBarrio()
    {
        $this->__load();
        return parent::getBarrio();
    }

    public function setCalle(\BecasMds\PersonaBundle\Entity\Calle $calle = NULL)
    {
        $this->__load();
        return parent::setCalle($calle);
    }

    public function getCalle()
    {
        $this->__load();
        return parent::getCalle();
    }

    public function addPersona(\BecasMds\PersonaBundle\Entity\Persona $persona = NULL)
    {
        $this->__load();
        return parent::addPersona($persona);
    }

    public function setPersona(\BecasMds\PersonaBundle\Entity\Persona $persona = NULL)
    {
        $this->__load();
        return parent::setPersona($persona);
    }

    public function getPersona()
    {
        $this->__load();
        return parent::getPersona();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'numero', 'dpto', 'piso', 'edificio', 'manzana', 'tira', 'parcela', 'quinta', 'unidadFuncional', 'latitude', 'longitude', 'referencias', 'localidad', 'departamento', 'barrio', 'calle', 'persona');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}