<?php

namespace Proxies\__CG__\BecasMds\CertificacionBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Certificacion extends \BecasMds\CertificacionBundle\Entity\Certificacion implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setMonto($monto)
    {
        $this->__load();
        return parent::setMonto($monto);
    }

    public function getMonto()
    {
        $this->__load();
        return parent::getMonto();
    }

    public function setDescuentoDias($descuentoDias)
    {
        $this->__load();
        return parent::setDescuentoDias($descuentoDias);
    }

    public function getDescuentoDias()
    {
        $this->__load();
        return parent::getDescuentoDias();
    }

    public function setTotalPagar($totalPagar)
    {
        $this->__load();
        return parent::setTotalPagar($totalPagar);
    }

    public function getTotalPagar()
    {
        $this->__load();
        return parent::getTotalPagar();
    }

    public function setCertificado($certificado)
    {
        $this->__load();
        return parent::setCertificado($certificado);
    }

    public function getCertificado()
    {
        $this->__load();
        return parent::getCertificado();
    }

    public function setMesCertificacion($mesCertificacion)
    {
        $this->__load();
        return parent::setMesCertificacion($mesCertificacion);
    }

    public function getMesCertificacion()
    {
        $this->__load();
        return parent::getMesCertificacion();
    }

    public function setBecadobeca(\BecasMds\BecaBundle\Entity\BecadoBeca $becadobeca = NULL)
    {
        $this->__load();
        return parent::setBecadobeca($becadobeca);
    }

    public function getBecadobeca()
    {
        $this->__load();
        return parent::getBecadobeca();
    }

    public function getBecaMonto()
    {
        $this->__load();
        return parent::getBecaMonto();
    }

    public function getBecado()
    {
        $this->__load();
        return parent::getBecado();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'monto', 'descuentoDias', 'totalPagar', 'certificado', 'mesCertificacion', 'becadobeca');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}