<?php

namespace Proxies\__CG__\BecasMds\PersonaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Becado extends \BecasMds\PersonaBundle\Entity\Becado implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setPresentaCertificacion($presentaCertificacion)
    {
        $this->__load();
        return parent::setPresentaCertificacion($presentaCertificacion);
    }

    public function getPresentaCertificacion()
    {
        $this->__load();
        return parent::getPresentaCertificacion();
    }

    public function setActivo($activo)
    {
        $this->__load();
        return parent::setActivo($activo);
    }

    public function getActivo()
    {
        $this->__load();
        return parent::getActivo();
    }

    public function setFechaAlta($fechaAlta)
    {
        $this->__load();
        return parent::setFechaAlta($fechaAlta);
    }

    public function getFechaAlta()
    {
        $this->__load();
        return parent::getFechaAlta();
    }

    public function setFechaBaja($fechaBaja)
    {
        $this->__load();
        return parent::setFechaBaja($fechaBaja);
    }

    public function getFechaBaja()
    {
        $this->__load();
        return parent::getFechaBaja();
    }

    public function setDni($dni)
    {
        $this->__load();
        return parent::setDni($dni);
    }

    public function getDni()
    {
        $this->__load();
        return parent::getDni();
    }

    public function setApellidos($apellidos)
    {
        $this->__load();
        return parent::setApellidos($apellidos);
    }

    public function getBecadoLista()
    {
        $this->__load();
        return parent::getBecadoLista();
    }

    public function getApellidos()
    {
        $this->__load();
        return parent::getApellidos();
    }

    public function setNombres($nombres)
    {
        $this->__load();
        return parent::setNombres($nombres);
    }

    public function getNombres()
    {
        $this->__load();
        return parent::getNombres();
    }

    public function setTelefono($telefono)
    {
        $this->__load();
        return parent::setTelefono($telefono);
    }

    public function getTelefono()
    {
        $this->__load();
        return parent::getTelefono();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setDependencia(\BecasMds\PersonaBundle\Entity\Dependencia $dependencia = NULL)
    {
        $this->__load();
        return parent::setDependencia($dependencia);
    }

    public function getDependencia()
    {
        $this->__load();
        return parent::getDependencia();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setLugarAfectacion(\BecasMds\PersonaBundle\Entity\LugarAfectacion $lugarAfectacion = NULL)
    {
        $this->__load();
        return parent::setLugarAfectacion($lugarAfectacion);
    }

    public function getLugarAfectacion()
    {
        $this->__load();
        return parent::getLugarAfectacion();
    }

    public function addFormacion(\BecasMds\FormacionBundle\Entity\Formacion $formacion)
    {
        $this->__load();
        return parent::addFormacion($formacion);
    }

    public function removeFormacion(\BecasMds\FormacionBundle\Entity\Formacion $formacion)
    {
        $this->__load();
        return parent::removeFormacion($formacion);
    }

    public function getFormacion()
    {
        $this->__load();
        return parent::getFormacion();
    }

    public function addDomicilio(\BecasMds\PersonaBundle\Entity\Domicilio $domicilio)
    {
        $this->__load();
        return parent::addDomicilio($domicilio);
    }

    public function removeDomicilio(\BecasMds\PersonaBundle\Entity\Domicilio $domicilio)
    {
        $this->__load();
        return parent::removeDomicilio($domicilio);
    }

    public function getDomicilio()
    {
        $this->__load();
        return parent::getDomicilio();
    }

    public function setReferente(\BecasMds\PersonaBundle\Entity\Referente $referente = NULL)
    {
        $this->__load();
        return parent::setReferente($referente);
    }

    public function getReferente()
    {
        $this->__load();
        return parent::getReferente();
    }

    public function addBecadobeca(\BecasMds\BecaBundle\Entity\BecadoBeca $becadobeca)
    {
        $this->__load();
        return parent::addBecadobeca($becadobeca);
    }

    public function removeBecadobeca(\BecasMds\BecaBundle\Entity\BecadoBeca $becadobeca)
    {
        $this->__load();
        return parent::removeBecadobeca($becadobeca);
    }

    public function getBecadobeca()
    {
        $this->__load();
        return parent::getBecadobeca();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'dni', 'apellidos', 'nombres', 'telefono', 'email', 'formacion', 'domicilio', 'presentaCertificacion', 'activo', 'fechaAlta', 'fechaBaja', 'referente', 'dependencia', 'lugarAfectacion', 'becadobeca');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}