<?php

namespace Proxies\__CG__\BecasMds\FormacionBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Formacion extends \BecasMds\FormacionBundle\Entity\Formacion implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setOficio(\BecasMds\FormacionBundle\Entity\Oficio $oficio = NULL)
    {
        $this->__load();
        return parent::setOficio($oficio);
    }

    public function getOficio()
    {
        $this->__load();
        return parent::getOficio();
    }

    public function setNivelEducativo(\BecasMds\FormacionBundle\Entity\NivelEducativo $nivelEducativo = NULL)
    {
        $this->__load();
        return parent::setNivelEducativo($nivelEducativo);
    }

    public function getNivelEducativo()
    {
        $this->__load();
        return parent::getNivelEducativo();
    }

    public function setInstitucion(\BecasMds\FormacionBundle\Entity\Institucion $institucion = NULL)
    {
        $this->__load();
        return parent::setInstitucion($institucion);
    }

    public function getInstitucion()
    {
        $this->__load();
        return parent::getInstitucion();
    }

    public function setPerfil(\BecasMds\FormacionBundle\Entity\Perfil $perfil = NULL)
    {
        $this->__load();
        return parent::setPerfil($perfil);
    }

    public function getPerfil()
    {
        $this->__load();
        return parent::getPerfil();
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setProfesion(\BecasMds\FormacionBundle\Entity\Profesion $profesion = NULL)
    {
        $this->__load();
        return parent::setProfesion($profesion);
    }

    public function getProfesion()
    {
        $this->__load();
        return parent::getProfesion();
    }

    public function addPersona(\BecasMds\PersonaBundle\Entity\Persona $persona = NULL)
    {
        $this->__load();
        return parent::addPersona($persona);
    }

    public function setPersona(\BecasMds\PersonaBundle\Entity\Persona $persona = NULL)
    {
        $this->__load();
        return parent::setPersona($persona);
    }

    public function getPersona()
    {
        $this->__load();
        return parent::getPersona();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'descripcion', 'oficio', 'nivelEducativo', 'institucion', 'profesion', 'perfil', 'persona');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}