institucion:
    pattern:  /
    defaults: { _controller: "FormacionBundle:Institucion:index" }

institucion_show:
    pattern:  /{id}/show
    defaults: { _controller: "FormacionBundle:Institucion:show" }

institucion_new:
    pattern:  /new
    defaults: { _controller: "FormacionBundle:Institucion:new" }

institucion_create:
    pattern:  /create
    defaults: { _controller: "FormacionBundle:Institucion:create" }
    requirements: { _method: post }

institucion_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FormacionBundle:Institucion:edit" }

institucion_update:
    pattern:  /{id}/update
    defaults: { _controller: "FormacionBundle:Institucion:update" }
    requirements: { _method: post|put }

institucion_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FormacionBundle:Institucion:delete" }
    requirements: { _method: post|delete }
