oficio:
    pattern:  /
    defaults: { _controller: "FormacionBundle:Oficio:index" }

oficio_show:
    pattern:  /{id}/show
    defaults: { _controller: "FormacionBundle:Oficio:show" }

oficio_new:
    pattern:  /new
    defaults: { _controller: "FormacionBundle:Oficio:new" }

oficio_create:
    pattern:  /create
    defaults: { _controller: "FormacionBundle:Oficio:create" }
    requirements: { _method: post }

oficio_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FormacionBundle:Oficio:edit" }

oficio_update:
    pattern:  /{id}/update
    defaults: { _controller: "FormacionBundle:Oficio:update" }
    requirements: { _method: post|put }

oficio_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FormacionBundle:Oficio:delete" }
    requirements: { _method: post|delete }
