parameters:
#    persona.example.class: BecasMds\PersonaBundle\Example

services:
#    persona.example:
#        class: %persona.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
