<?php

namespace BecasMds\FormacionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SecundarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecundarioRepository extends EntityRepository
{
}
