<?php

namespace BecasMds\FormacionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UniversidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniversidadRepository extends EntityRepository
{
}
