<?php

namespace BecasMds\CertificacionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CertificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificacionRepository extends EntityRepository
{
}
