<?php

namespace BecasMds\PersonaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LugarAfectacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LugarAfectacionRepository extends EntityRepository
{
}
