<?php

namespace BecasMds\BecaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BecaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BecaRepository extends EntityRepository
{
}
