<?php

namespace BecasMds\BecaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BecadoBecaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BecadoBecaRepository extends EntityRepository
{
}
