<?php

namespace Proxies\__CG__\BecasMds\CertificacionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Certificacion extends \BecasMds\CertificacionBundle\Entity\Certificacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'id', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'becatipo', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'becafuncion', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'monto', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'descuentoDias', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'totalPagar', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'certificado', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'mesCertificacion', 'becadobeca', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'createdBy', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'updatedBy', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'createdAt', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'id', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'becatipo', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'becafuncion', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'monto', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'descuentoDias', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'totalPagar', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'certificado', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'mesCertificacion', 'becadobeca', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'createdBy', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'updatedBy', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'createdAt', '' . "\0" . 'BecasMds\\CertificacionBundle\\Entity\\Certificacion' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Certificacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonto($monto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonto', [$monto]);

        return parent::setMonto($monto);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonto', []);

        return parent::getMonto();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescuentoDias($descuentoDias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescuentoDias', [$descuentoDias]);

        return parent::setDescuentoDias($descuentoDias);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescuentoDias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescuentoDias', []);

        return parent::getDescuentoDias();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalPagar($totalPagar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalPagar', [$totalPagar]);

        return parent::setTotalPagar($totalPagar);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalPagar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalPagar', []);

        return parent::getTotalPagar();
    }

    /**
     * {@inheritDoc}
     */
    public function setCertificado($certificado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCertificado', [$certificado]);

        return parent::setCertificado($certificado);
    }

    /**
     * {@inheritDoc}
     */
    public function getCertificado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCertificado', []);

        return parent::getCertificado();
    }

    /**
     * {@inheritDoc}
     */
    public function setMesCertificacion($mesCertificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMesCertificacion', [$mesCertificacion]);

        return parent::setMesCertificacion($mesCertificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getMesCertificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMesCertificacion', []);

        return parent::getMesCertificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setBecadobeca(\BecasMds\BecaBundle\Entity\BecadoBeca $becadobeca = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBecadobeca', [$becadobeca]);

        return parent::setBecadobeca($becadobeca);
    }

    /**
     * {@inheritDoc}
     */
    public function getBecadobeca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBecadobeca', []);

        return parent::getBecadobeca();
    }

    /**
     * {@inheritDoc}
     */
    public function getBecaMonto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBecaMonto', []);

        return parent::getBecaMonto();
    }

    /**
     * {@inheritDoc}
     */
    public function getBecado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBecado', []);

        return parent::getBecado();
    }

    /**
     * {@inheritDoc}
     */
    public function setBecatipo($becatipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBecatipo', [$becatipo]);

        return parent::setBecatipo($becatipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getBecatipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBecatipo', []);

        return parent::getBecatipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setBecafuncion($becafuncion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBecafuncion', [$becafuncion]);

        return parent::setBecafuncion($becafuncion);
    }

    /**
     * {@inheritDoc}
     */
    public function getBecafuncion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBecafuncion', []);

        return parent::getBecafuncion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$createdBy]);

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy($updatedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$updatedBy]);

        return parent::setUpdatedBy($updatedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

}
