<?php

namespace Proxies\__CG__\BecasMds\PersonaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Domicilio extends \BecasMds\PersonaBundle\Entity\Domicilio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'id', 'localidad', 'departamento', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'barrio', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'calle', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'numero', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'dpto', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'piso', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'edificio', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'manzana', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'tira', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'parcela', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'quinta', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'unidadFuncional', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'latitude', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'longitude', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'referencias', 'persona', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'createdBy', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'updatedBy', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'createdAt', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'id', 'localidad', 'departamento', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'barrio', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'calle', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'numero', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'dpto', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'piso', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'edificio', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'manzana', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'tira', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'parcela', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'quinta', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'unidadFuncional', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'latitude', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'longitude', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'referencias', 'persona', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'createdBy', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'updatedBy', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'createdAt', '' . "\0" . 'BecasMds\\PersonaBundle\\Entity\\Domicilio' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Domicilio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', [$numero]);

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setDpto($dpto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDpto', [$dpto]);

        return parent::setDpto($dpto);
    }

    /**
     * {@inheritDoc}
     */
    public function getDpto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDpto', []);

        return parent::getDpto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPiso($piso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPiso', [$piso]);

        return parent::setPiso($piso);
    }

    /**
     * {@inheritDoc}
     */
    public function getPiso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPiso', []);

        return parent::getPiso();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdificio($edificio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdificio', [$edificio]);

        return parent::setEdificio($edificio);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdificio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdificio', []);

        return parent::getEdificio();
    }

    /**
     * {@inheritDoc}
     */
    public function setManzana($manzana)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManzana', [$manzana]);

        return parent::setManzana($manzana);
    }

    /**
     * {@inheritDoc}
     */
    public function getManzana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManzana', []);

        return parent::getManzana();
    }

    /**
     * {@inheritDoc}
     */
    public function setTira($tira)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTira', [$tira]);

        return parent::setTira($tira);
    }

    /**
     * {@inheritDoc}
     */
    public function getTira()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTira', []);

        return parent::getTira();
    }

    /**
     * {@inheritDoc}
     */
    public function setParcela($parcela)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParcela', [$parcela]);

        return parent::setParcela($parcela);
    }

    /**
     * {@inheritDoc}
     */
    public function getParcela()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParcela', []);

        return parent::getParcela();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuinta($quinta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuinta', [$quinta]);

        return parent::setQuinta($quinta);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuinta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuinta', []);

        return parent::getQuinta();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidadFuncional($unidadFuncional)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidadFuncional', [$unidadFuncional]);

        return parent::setUnidadFuncional($unidadFuncional);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidadFuncional()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidadFuncional', []);

        return parent::getUnidadFuncional();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoDomicilio($tipoDomicilio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoDomicilio', [$tipoDomicilio]);

        return parent::setTipoDomicilio($tipoDomicilio);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoDomicilio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoDomicilio', []);

        return parent::getTipoDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', [$latitude]);

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', []);

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', [$longitude]);

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', []);

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferencias($referencias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferencias', [$referencias]);

        return parent::setReferencias($referencias);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferencias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferencias', []);

        return parent::getReferencias();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalidad(\BecasMds\PersonaBundle\Entity\Localidad $localidad = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalidad', [$localidad]);

        return parent::setLocalidad($localidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalidad', []);

        return parent::getLocalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartamento(\BecasMds\PersonaBundle\Entity\Departamento $departamento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartamento', [$departamento]);

        return parent::setDepartamento($departamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartamento', []);

        return parent::getDepartamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setBarrio(\BecasMds\PersonaBundle\Entity\Barrio $barrio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBarrio', [$barrio]);

        return parent::setBarrio($barrio);
    }

    /**
     * {@inheritDoc}
     */
    public function getBarrio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBarrio', []);

        return parent::getBarrio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalle(\BecasMds\PersonaBundle\Entity\Calle $calle = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalle', [$calle]);

        return parent::setCalle($calle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalle', []);

        return parent::getCalle();
    }

    /**
     * {@inheritDoc}
     */
    public function addPersona(\BecasMds\PersonaBundle\Entity\Persona $persona = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPersona', [$persona]);

        return parent::addPersona($persona);
    }

    /**
     * {@inheritDoc}
     */
    public function setPersona(\BecasMds\PersonaBundle\Entity\Persona $persona = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersona', [$persona]);

        return parent::setPersona($persona);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersona()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersona', []);

        return parent::getPersona();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$createdBy]);

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy($updatedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$updatedBy]);

        return parent::setUpdatedBy($updatedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

}
