parameters:
#    usuario.example.class: BecasMds\UsuarioBundle\Example

services:
#    usuario.example:
#        class: %usuario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    usuario_user.registration.form.type:
        class: BecasMds\UsuarioBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: usuario_user_registration }
    usuario_user.profile.form.type:
        class: BecasMds\UsuarioBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: usuario_user_profile }